name=input("Enter student's name.")
course=input("Enter student's course.")
roll=input("Enter roll number")
print("Enter marks")
science=int(input("Science"))
maths=int(input("Maths"))
english=int(input("English"))
print("Name : ",name)
print("Course : ",course)
print("Roll no. : ",roll)
print("Science \t Maths \t English")
print(science,"\t",maths,"\t",english,"\n")
print("Total : ",(science+maths+english))
print("Percentage : ",(science+maths+english)/3,"%")
